2023-01-08 12:13:01,524 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 12:17:33,284 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 12:19:20,690 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 12:33:37,774 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 12:36:10,403 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 12:58:10,260 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 13:02:49,799 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1045b80a0>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:02:55,936 - Comm - ERROR - No such comm target registered: jupyter.widget.control
2023-01-08 13:13:32,469 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10292e820>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:31:35,203 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x107246f70>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:40:14,946 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x107d126a0>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:42:43,624 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x12420cd30>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:44:57,503 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10604e6a0>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:48:25,816 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x105955f70>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 13:49:19,907 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x104d3b820>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 14:07:54,838 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x109891c40>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 14:23:05,031 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x107aa1f40>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 14:32:24,010 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x107dd6f70>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 14:36:12,387 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1032b48e0>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 14:37:09,642 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x107b7ef40>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 15:02:10,238 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10603fa60>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
2023-01-08 15:02:39,900 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Kernel.poll_control_queue() running at /Users/k9/.pyenv/versions/3.9.11/envs/kedro-on-aws/lib/python3.9/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x12f07ee50>()]> cb=[_chain_future.<locals>._call_set_state() at /Users/k9/.pyenv/versions/3.9.11/lib/python3.9/asyncio/futures.py:391]>
